package PixelArt;
import java.awt.*;
import java.awt.image.BufferedImage;

public class GeneradorImage {
	 static Color rosaOP = new Color(188,3,88,255);
	 static Color rosaClaro = new Color(254,167,222,255);
	 static Color Brown = new Color(156,90,60);
	 static Color rosaBrillo=new Color(254,105,177,255);
	 static Color rosaChillon=new Color(254,23,156,255);
	 static Color rojoOP=new Color(202,0,0,255);
	 static Color rosaRojo=new Color(255,82,93,255);
	 static Color moradoOP= new Color (110,0,26,255);
	 
	 
	 
	 
	    public static BufferedImage Imagen1(){
	        int width = 1200, height = 1200, PIXEL_SIZE = 40;
	        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
	        Graphics2D graphics2D = bufferedImage.createGraphics();
	        ImagenConfig.fondo(bufferedImage, Color.WHITE);
	        ImagenConfig.cuadricula(bufferedImage, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 7, 5, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 8, 5, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 9, 5, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 10, 5, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 11, 5, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 5, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 5, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 5, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 5, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 21, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 5, 22, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 4, 23, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 4, 24, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 4, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 5, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 7, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 8, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 9, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 10, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 11, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 12, 27, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 13, 27, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 14, 27, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 15, 27, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 16, 27, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17, 27, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 19, 26, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 20, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 21, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 22, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 22, 24, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 23, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 24, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 26, 25, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 27, 24, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 27, 23, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 27, 22, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 26, 21, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 25, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 24, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 24, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 23, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 22, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 21, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 21, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 20, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 19, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 16, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 15, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 14, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 13, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 12, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 6, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 6, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 17, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 18, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 6, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 17, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 18, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 6, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 17, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 18, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 10, PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 17,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 18,11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 11, PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 17,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 18,12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 12, PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 17,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 18,13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,rosaClaro, 24, 13,PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18,14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,rosaClaro, 24, 14,PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18,15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,rosaClaro, 24, 15,PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,16,PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18,16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,rosaClaro, 24, 16,PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18,17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,rosaClaro, 24, 17,PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18,18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,rosaClaro, 24, 18,PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 17,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 18,19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,rosaClaro, 24, 19,PIXEL_SIZE);
	        
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 7, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 8,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 9,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 10,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 11,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 12,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 13,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 14,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 15,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 16,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 17,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 18,20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 19, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 20, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 21, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 22, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaClaro, 23, 20, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage,Color.BLACK, 24, 20,PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, rosaBrillo, 23, 20, PIXEL_SIZE);
	        
	        
	        return bufferedImage;
	    }
	    public static BufferedImage Imagen2(){
	        int width = 800, height = 800, PIXEL_SIZE = 40;
	        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
	        Graphics2D graphics2D = bufferedImage.createGraphics();
	        ImagenConfig.fondo(bufferedImage, Color.WHITE);
	        ImagenConfig.cuadricula(bufferedImage, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 8, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 7, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 11, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 12, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 13, 13, PIXEL_SIZE);
	        return bufferedImage;
	    }
	    public static BufferedImage Imagen3(){
	        int width = 800, height = 800, PIXEL_SIZE = 40;
	        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
	        Graphics2D graphics2D = bufferedImage.createGraphics();
	        ImagenConfig.fondo(bufferedImage, Color.WHITE);
	        ImagenConfig.cuadricula(bufferedImage, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 7, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 8, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 9, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 7, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 8, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 9, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 10,7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.WHITE, 7, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 8, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 9, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.WHITE, 10, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 11, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 7, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.ORANGE, 8,9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.ORANGE, 9, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 10, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 11, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.ORANGE, 6, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 6, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 7, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 8, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 9, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 10,7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.BLACK, 9, 15, PIXEL_SIZE);
	       
	        return bufferedImage;
	    }
	    public static BufferedImage Imagen4(){
	        int width = 800, height = 800, PIXEL_SIZE = 40;
	        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
	        Graphics2D graphics2D = bufferedImage.createGraphics();
	        ImagenConfig.fondo(bufferedImage, Color.WHITE);
	        ImagenConfig.cuadricula(bufferedImage, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 8, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 11, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 8, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 7, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 6, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 11, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 12, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 13, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 9, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 10, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 7, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 8, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 7, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 8, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 11, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 12, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 11, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 12, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 9, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 10, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 9, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 10, 9, PIXEL_SIZE);
	        return bufferedImage;
	    }
	    public static BufferedImage Imagen5(){
	        int width = 800, height = 800, PIXEL_SIZE = 40;
	        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
	        Graphics2D graphics2D = bufferedImage.createGraphics();
	        ImagenConfig.fondo(bufferedImage, Color.WHITE);
	        ImagenConfig.cuadricula(bufferedImage, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 8, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 11, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 19, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 18, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 17, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 16, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 15, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 14, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 13, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 12, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 9, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 10, 11, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 8, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 7, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 6, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 5, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 11, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 12, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 13, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.GREEN, 14, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 9, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 10, 10, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 8, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 9, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 10, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 11, 9, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 7, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 8, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 11, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 12, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 7, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 8, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 11, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 12, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 8, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 9, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 10, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 11, 6, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 9, 5, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Color.YELLOW, 10, 5, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 9, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 10, 8, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 9, 7, PIXEL_SIZE);
	        ImagenConfig.Pixel(bufferedImage, Brown, 10, 7, PIXEL_SIZE);

	        return bufferedImage;
	    }

}
